In [69]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.model_selection import train_test_split

In [70]:
# Reading raw data

df_raw = pd.read_csv("Data/heart_2022_with_nans.csv")
df_raw.head(5)

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,...,HeightInMeters,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,Female,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,No,8.0,NaN,No,...,NaN,NaN,NaN,No,No,Yes,No,"Yes, received tetanus shot but not sure what type",No,No
1,Alabama,Female,Excellent,0.0,0.0,NaN,No,6.0,NaN,No,...,1.60,68.04,26.57,No,No,No,No,"No, did not receive any tetanus shot in the pa...",No,No
2,Alabama,Female,Very good,2.0,3.0,Within past year (anytime less than 12 months ...,Yes,5.0,NaN,No,...,1.57,63.50,25.61,No,No,No,No,NaN,No,Yes
3,Alabama,Female,Excellent,0.0,0.0,Within past year (anytime less than 12 months ...,Yes,7.0,NaN,No,...,1.65,63.50,23.30,No,No,Yes,Yes,"No, did not receive any tetanus shot in the pa...",No,No
4,Alabama,Female,Fair,2.0,0.0,Within past year (anytime less than 12 months ...,Yes,9.0,NaN,No,...,1.57,53.98,21.77,Yes,No,No,Yes,"No, did not receive any tetanus shot in the pa...",No,No

In [71]:
# Checking number of nulls value in dataframe
df_raw.isnull().sum()

State                            0
Sex                              0
GeneralHealth                 1198
PhysicalHealthDays           10927
MentalHealthDays              9067
LastCheckupTime               8308
PhysicalActivities            1093
SleepHours                    5453
RemovedTeeth                 11360
HadHeartAttack                3065
HadAngina                     4405
HadStroke                     1557
HadAsthma                     1773
HadSkinCancer                 3143
HadCOPD                       2219
HadDepressiveDisorder         2812
HadKidneyDisease              1926
HadArthritis                  2633
HadDiabetes                   1087
DeafOrHardOfHearing          20647
BlindOrVisionDifficulty      21564
DifficultyConcentrating      24240
DifficultyWalking            24012
DifficultyDressingBathing    23915
DifficultyErrands            25656
SmokerStatus                 35462
ECigaretteUsage              35660
ChestScan                    56046
RaceEthnicityCategory        14057
AgeCategory                   9079
HeightInMeters               28652
WeightInKilograms            42078
BMI                          48806
AlcoholDrinkers              46574
HIVTesting                   66127
FluVaxLast12                 47121
PneumoVaxEver                77040
TetanusLast10Tdap            82516
HighRiskLastYear             50623
CovidPos                     50764
dtype: int64

In [72]:
df_raw.shape

(445132, 40)

In [185]:
# Dropping null values from dataframe
df_nn = df_raw.dropna().reset_index(drop=True)

In [136]:
df_nn.shape

(246022, 40)

In [168]:
df_nn.head()

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,...,HeightInMeters,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,0,Very good,4.0,0.0,Within past year (anytime less than 12 months ...,Yes,9.0,None of them,0,...,1.60,71.67,27.99,0,0,1,1,"Yes, received Tdap",0,No
1,Alabama,1,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,Yes,6.0,None of them,0,...,1.78,95.25,30.13,0,0,1,1,"Yes, received tetanus shot but not sure what type",0,No
2,Alabama,1,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,No,8.0,"6 or more, but not all",0,...,1.85,108.86,31.66,1,0,0,1,"No, did not receive any tetanus shot in the pa...",0,Yes
3,Alabama,0,Fair,5.0,0.0,Within past year (anytime less than 12 months ...,Yes,9.0,None of them,0,...,1.70,90.72,31.32,0,0,1,1,"No, did not receive any tetanus shot in the pa...",0,Yes
4,Alabama,0,Good,3.0,15.0,Within past year (anytime less than 12 months ...,Yes,5.0,1 to 5,0,...,1.55,79.38,33.07,0,0,1,1,"No, did not receive any tetanus shot in the pa...",0,No

In [75]:
df_nn.isnull().sum()

State                        0
Sex                          0
GeneralHealth                0
PhysicalHealthDays           0
MentalHealthDays             0
LastCheckupTime              0
PhysicalActivities           0
SleepHours                   0
RemovedTeeth                 0
HadHeartAttack               0
HadAngina                    0
HadStroke                    0
HadAsthma                    0
HadSkinCancer                0
HadCOPD                      0
HadDepressiveDisorder        0
HadKidneyDisease             0
HadArthritis                 0
HadDiabetes                  0
DeafOrHardOfHearing          0
BlindOrVisionDifficulty      0
DifficultyConcentrating      0
DifficultyWalking            0
DifficultyDressingBathing    0
DifficultyErrands            0
SmokerStatus                 0
ECigaretteUsage              0
ChestScan                    0
RaceEthnicityCategory        0
AgeCategory                  0
HeightInMeters               0
WeightInKilograms            0
BMI                          0
AlcoholDrinkers              0
HIVTesting                   0
FluVaxLast12                 0
PneumoVaxEver                0
TetanusLast10Tdap            0
HighRiskLastYear             0
CovidPos                     0
dtype: int64

In [76]:
df_nn.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 246022 entries, 342 to 445130
Data columns (total 40 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   State                      246022 non-null  object
 1   Sex                        246022 non-null  object
 2   GeneralHealth              246022 non-null  object
 3   PhysicalHealthDays         246022 non-null  float64
 4   MentalHealthDays           246022 non-null  float64
 5   LastCheckupTime            246022 non-null  object
 6   PhysicalActivities         246022 non-null  object
 7   SleepHours                 246022 non-null  float64
 8   RemovedTeeth               246022 non-null  object
 9   HadHeartAttack             246022 non-null  object
 10  HadAngina                  246022 non-null  object
 11  HadStroke                  246022 non-null  object
 12  HadAsthma                  246022 non-null  object
 13  HadSkinCancer              246022 non-null  object
 14  HadCOPD                    246022 non-null  object
 15  HadDepressiveDisorder      246022 non-null  object
 16  HadKidneyDisease           246022 non-null  object
 17  HadArthritis               246022 non-null  object
 18  HadDiabetes                246022 non-null  object
 19  DeafOrHardOfHearing        246022 non-null  object
 20  BlindOrVisionDifficulty    246022 non-null  object
 21  DifficultyConcentrating    246022 non-null  object
 22  DifficultyWalking          246022 non-null  object
 23  DifficultyDressingBathing  246022 non-null  object
 24  DifficultyErrands          246022 non-null  object
 25  SmokerStatus               246022 non-null  object
 26  ECigaretteUsage            246022 non-null  object
 27  ChestScan                  246022 non-null  object
 28  RaceEthnicityCategory      246022 non-null  object
 29  AgeCategory                246022 non-null  object
 30  HeightInMeters             246022 non-null  float64
 31  WeightInKilograms          246022 non-null  float64
 32  BMI                        246022 non-null  float64
 33  AlcoholDrinkers            246022 non-null  object
 34  HIVTesting                 246022 non-null  object
 35  FluVaxLast12               246022 non-null  object
 36  PneumoVaxEver              246022 non-null  object
 37  TetanusLast10Tdap          246022 non-null  object
 38  HighRiskLastYear           246022 non-null  object
 39  CovidPos                   246022 non-null  object
dtypes: float64(6), object(34)
memory usage: 77.0+ MB

In [77]:
df_nn.describe()

,PhysicalHealthDays,MentalHealthDays,SleepHours,HeightInMeters,WeightInKilograms,BMI
count,246022.000000,246022.000000,246022.000000,246022.000000,246022.000000,246022.000000
mean,4.119026,4.167140,7.021331,1.705150,83.615179,28.668136
std,8.405844,8.102687,1.440681,0.106654,21.323156,6.513973
min,0.000000,0.000000,1.000000,0.910000,28.120000,12.020000
25%,0.000000,0.000000,6.000000,1.630000,68.040000,24.270000
50%,0.000000,0.000000,7.000000,1.700000,81.650000,27.460000
75%,3.000000,4.000000,8.000000,1.780000,95.250000,31.890000
max,30.000000,30.000000,24.000000,2.410000,292.570000,97.650000

In [78]:
for col in df_nn.columns:
    print(col)
    print(df_nn[col].value_counts())

State
Washington              15000
Maryland                 9165
Minnesota                9161
Ohio                     8995
New York                 8923
Texas                    7408
Florida                  7315
Kansas                   6145
Wisconsin                6126
Maine                    6013
Iowa                     5672
Hawaii                   5596
Virginia                 5565
Indiana                  5502
South Carolina           5471
Massachusetts            5465
Arizona                  5462
Utah                     5373
Michigan                 5370
Colorado                 5159
Nebraska                 5107
California               5096
Connecticut              5053
Georgia                  4978
Vermont                  4845
South Dakota             4405
Montana                  4264
Missouri                 4195
New Jersey               3967
New Hampshire            3756
Puerto Rico              3589
Idaho                    3468
Alaska                   3205
Rhode Island             3112
Oregon                   3049
Louisiana                3010
West Virginia            2974
New Mexico               2968
Oklahoma                 2941
Arkansas                 2940
Pennsylvania             2729
Tennessee                2725
Illinois                 2607
North Carolina           2551
North Dakota             2498
Mississippi              2438
Kentucky                 2413
Wyoming                  2410
Delaware                 2155
Alabama                  1902
Nevada                   1769
District of Columbia     1725
Guam                     1549
Virgin Islands            743
Name: State, dtype: int64
Sex
Female    127811
Male      118211
Name: Sex, dtype: int64
GeneralHealth
Very good    86999
Good         77409
Excellent    41525
Fair         30659
Poor          9430
Name: GeneralHealth, dtype: int64
PhysicalHealthDays
0.0     152802
30.0     17160
2.0      14728
1.0      10058
3.0       9137
5.0       8939
10.0      6068
7.0       5221
4.0       4906
15.0      4845
20.0      2950
14.0      2813
6.0       1421
25.0      1123
8.0        961
12.0       610
21.0       584
28.0       365
9.0        211
29.0       178
18.0       151
16.0       126
27.0       103
17.0       101
11.0        95
13.0        87
22.0        72
26.0        64
24.0        60
23.0        54
19.0        29
Name: PhysicalHealthDays, dtype: int64
MentalHealthDays
0.0     150454
2.0      13810
30.0     13702
5.0      11623
3.0       8849
10.0      8831
1.0       8244
15.0      8061
20.0      4925
4.0       4568
7.0       4485
25.0      1647
14.0      1573
6.0       1326
8.0        973
12.0       715
28.0       484
21.0       301
29.0       261
18.0       166
16.0       165
9.0        145
17.0       132
27.0       113
22.0       101
13.0        96
11.0        69
24.0        68
26.0        59
23.0        51
19.0        25
Name: MentalHealthDays, dtype: int64
LastCheckupTime
Within past year (anytime less than 12 months ago)         198153
Within past 2 years (1 year but less than 2 years ago)      23227
Within past 5 years (2 years but less than 5 years ago)     13744
5 or more years ago                                         10898
Name: LastCheckupTime, dtype: int64
PhysicalActivities
Yes    191318
No      54704
Name: PhysicalActivities, dtype: int64
SleepHours
7.0     76447
8.0     69927
6.0     53981
5.0     16417
9.0     11859
4.0      6478
10.0     5468
3.0      1618
12.0     1476
2.0       740
1.0       563
11.0      339
16.0      155
15.0      154
14.0      148
18.0       83
13.0       79
20.0       50
24.0       13
17.0       11
23.0        6
19.0        5
22.0        5
Name: SleepHours, dtype: int64
RemovedTeeth
None of them              131592
1 to 5                     74702
6 or more, but not all     25950
All                        13778
Name: RemovedTeeth, dtype: int64
HadHeartAttack
No     232587
Yes     13435
Name: HadHeartAttack, dtype: int64
HadAngina
No     231069
Yes     14953
Name: HadAngina, dtype: int64
HadStroke
No     235910
Yes     10112
Name: HadStroke, dtype: int64
HadAsthma
No     209493
Yes     36529
Name: HadAsthma, dtype: int64
HadSkinCancer
No     225001
Yes     21021
Name: HadSkinCancer, dtype: int64
HadCOPD
No     227028
Yes     18994
Name: HadCOPD, dtype: int64
HadDepressiveDisorder
No     195402
Yes     50620
Name: HadDepressiveDisorder, dtype: int64
HadKidneyDisease
No     234738
Yes     11284
Name: HadKidneyDisease, dtype: int64
HadArthritis
No     161139
Yes     84883
Name: HadArthritis, dtype: int64
HadDiabetes
No                                         204834
Yes                                         33813
No, pre-diabetes or borderline diabetes      5392
Yes, but only during pregnancy (female)      1983
Name: HadDiabetes, dtype: int64
DeafOrHardOfHearing
No     224990
Yes     21032
Name: DeafOrHardOfHearing, dtype: int64
BlindOrVisionDifficulty
No     233796
Yes     12226
Name: BlindOrVisionDifficulty, dtype: int64
DifficultyConcentrating
No     219802
Yes     26220
Name: DifficultyConcentrating, dtype: int64
DifficultyWalking
No     209952
Yes     36070
Name: DifficultyWalking, dtype: int64
DifficultyDressingBathing
No     237682
Yes      8340
Name: DifficultyDressingBathing, dtype: int64
DifficultyErrands
No     229638
Yes     16384
Name: DifficultyErrands, dtype: int64
SmokerStatus
Never smoked                             147737
Former smoker                             68527
Current smoker - now smokes every day     21659
Current smoker - now smokes some days      8099
Name: SmokerStatus, dtype: int64
ECigaretteUsage
Never used e-cigarettes in my entire life    190128
Not at all (right now)                        43281
Use them some days                             6658
Use them every day                             5955
Name: ECigaretteUsage, dtype: int64
ChestScan
No     141822
Yes    104200
Name: ChestScan, dtype: int64
RaceEthnicityCategory
White only, Non-Hispanic         186336
Hispanic                          22570
Black only, Non-Hispanic          19330
Other race only, Non-Hispanic     12205
Multiracial, Non-Hispanic          5581
Name: RaceEthnicityCategory, dtype: int64
AgeCategory
Age 65 to 69       28557
Age 60 to 64       26720
Age 70 to 74       25739
Age 55 to 59       22224
Age 50 to 54       19913
Age 75 to 79       18136
Age 80 or older    17816
Age 40 to 44       16973
Age 45 to 49       16753
Age 35 to 39       15614
Age 30 to 34       13346
Age 18 to 24       13122
Age 25 to 29       11109
Name: AgeCategory, dtype: int64
HeightInMeters
1.68    21694
1.63    20835
1.70    20054
1.78    19540
1.65    18825
        ...
1.92        1
2.36        1
1.44        1
1.38        1
2.21        1
Name: HeightInMeters, Length: 101, dtype: int64
WeightInKilograms
90.72     13066
81.65     12018
68.04     10365
72.57     10350
77.11      9725
          ...
238.14        1
200.49        1
166.47        1
205.02        1
30.39         1
Name: WeightInKilograms, Length: 516, dtype: int64
BMI
26.63    2727
27.46    2040
27.44    1964
24.41    1922
27.12    1893
         ...
41.65       1
33.24       1
25.57       1
13.64       1
45.28       1
Name: BMI, Length: 3514, dtype: int64
AlcoholDrinkers
Yes    135307
No     110715
Name: AlcoholDrinkers, dtype: int64
HIVTesting
No     161520
Yes     84502
Name: HIVTesting, dtype: int64
FluVaxLast12
Yes    131196
No     114826
Name: FluVaxLast12, dtype: int64
PneumoVaxEver
No     146130
Yes     99892
Name: PneumoVaxEver, dtype: int64
TetanusLast10Tdap
No, did not receive any tetanus shot in the past 10 years    81747
Yes, received tetanus shot but not sure what type            74119
Yes, received Tdap                                           70286
Yes, received tetanus shot, but not Tdap                     19870
Name: TetanusLast10Tdap, dtype: int64
HighRiskLastYear
No     235446
Yes     10576
Name: HighRiskLastYear, dtype: int64
CovidPos
No                                                               167306
Yes                                                               70324
Tested positive using home test without a health professional      8392
Name: CovidPos, dtype: int64

In [186]:
two_values_columns = []
for col in df_nn.columns:
    print(col)
    if len(df_nn[col].unique())==2:
        two_values_columns.append(col)

State
Sex
GeneralHealth
PhysicalHealthDays
MentalHealthDays
LastCheckupTime
PhysicalActivities
SleepHours
RemovedTeeth
HadHeartAttack
HadAngina
HadStroke
HadAsthma
HadSkinCancer
HadCOPD
HadDepressiveDisorder
HadKidneyDisease
HadArthritis
HadDiabetes
DeafOrHardOfHearing
BlindOrVisionDifficulty
DifficultyConcentrating
DifficultyWalking
DifficultyDressingBathing
DifficultyErrands
SmokerStatus
ECigaretteUsage
ChestScan
RaceEthnicityCategory
AgeCategory
HeightInMeters
WeightInKilograms
BMI
AlcoholDrinkers
HIVTesting
FluVaxLast12
PneumoVaxEver
TetanusLast10Tdap
HighRiskLastYear
CovidPos

In [138]:
for col in two_values_columns:
    print(col)
    print(df_nn[col].unique())

Sex
['Female' 'Male']
PhysicalActivities
['Yes' 'No']
HadHeartAttack
['No' 'Yes']
HadAngina
['No' 'Yes']
HadStroke
['No' 'Yes']
HadAsthma
['No' 'Yes']
HadSkinCancer
['No' 'Yes']
HadCOPD
['No' 'Yes']
HadDepressiveDisorder
['No' 'Yes']
HadKidneyDisease
['No' 'Yes']
HadArthritis
['Yes' 'No']
DeafOrHardOfHearing
['No' 'Yes']
BlindOrVisionDifficulty
['No' 'Yes']
DifficultyConcentrating
['No' 'Yes']
DifficultyWalking
['No' 'Yes']
DifficultyDressingBathing
['No' 'Yes']
DifficultyErrands
['No' 'Yes']
ChestScan
['No' 'Yes']
AlcoholDrinkers
['No' 'Yes']
HIVTesting
['No' 'Yes']
FluVaxLast12
['Yes' 'No']
PneumoVaxEver
['Yes' 'No']
HighRiskLastYear
['No' 'Yes']

In [190]:
# YES_NO_QUESTIONS = {'Yes':1,'No':0}

# df_cd['HadHeartAttack'] = df_cd['HadHeartAttack'].map(YES_NO_QUESTIONS)
for col in two_values_columns[1:]:
    df_nn.loc[df_nn[col]=='Yes',col]= 1
    df_nn.loc[df_nn[col]=='No',col]= 0

In [191]:
df_nn.head()

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,...,HeightInMeters,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,Female,Very good,4.0,0.0,Within past year (anytime less than 12 months ...,1,9.0,None of them,0,...,1.60,71.67,27.99,0,0,1,1,"Yes, received Tdap",0,No
1,Alabama,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,1,6.0,None of them,0,...,1.78,95.25,30.13,0,0,1,1,"Yes, received tetanus shot but not sure what type",0,No
2,Alabama,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,0,8.0,"6 or more, but not all",0,...,1.85,108.86,31.66,1,0,0,1,"No, did not receive any tetanus shot in the pa...",0,Yes
3,Alabama,Female,Fair,5.0,0.0,Within past year (anytime less than 12 months ...,1,9.0,None of them,0,...,1.70,90.72,31.32,0,0,1,1,"No, did not receive any tetanus shot in the pa...",0,Yes
4,Alabama,Female,Good,3.0,15.0,Within past year (anytime less than 12 months ...,1,5.0,1 to 5,0,...,1.55,79.38,33.07,0,0,1,1,"No, did not receive any tetanus shot in the pa...",0,No

In [192]:
df_nn.loc[df_nn['Sex']=='Male','Sex'] = 1
df_nn.loc[df_nn['Sex']=='Female','Sex']= 0

In [193]:
df_nn.head()

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,...,HeightInMeters,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,0,Very good,4.0,0.0,Within past year (anytime less than 12 months ...,1,9.0,None of them,0,...,1.60,71.67,27.99,0,0,1,1,"Yes, received Tdap",0,No
1,Alabama,1,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,1,6.0,None of them,0,...,1.78,95.25,30.13,0,0,1,1,"Yes, received tetanus shot but not sure what type",0,No
2,Alabama,1,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,0,8.0,"6 or more, but not all",0,...,1.85,108.86,31.66,1,0,0,1,"No, did not receive any tetanus shot in the pa...",0,Yes
3,Alabama,0,Fair,5.0,0.0,Within past year (anytime less than 12 months ...,1,9.0,None of them,0,...,1.70,90.72,31.32,0,0,1,1,"No, did not receive any tetanus shot in the pa...",0,Yes
4,Alabama,0,Good,3.0,15.0,Within past year (anytime less than 12 months ...,1,5.0,1 to 5,0,...,1.55,79.38,33.07,0,0,1,1,"No, did not receive any tetanus shot in the pa...",0,No

In [194]:
df_nn[two_values_columns] = df_nn[two_values_columns].apply(pd.to_numeric)

In [195]:
df_nn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246022 entries, 0 to 246021
Data columns (total 40 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   State                      246022 non-null  object
 1   Sex                        246022 non-null  int64
 2   GeneralHealth              246022 non-null  object
 3   PhysicalHealthDays         246022 non-null  float64
 4   MentalHealthDays           246022 non-null  float64
 5   LastCheckupTime            246022 non-null  object
 6   PhysicalActivities         246022 non-null  int64
 7   SleepHours                 246022 non-null  float64
 8   RemovedTeeth               246022 non-null  object
 9   HadHeartAttack             246022 non-null  int64
 10  HadAngina                  246022 non-null  int64
 11  HadStroke                  246022 non-null  int64
 12  HadAsthma                  246022 non-null  int64
 13  HadSkinCancer              246022 non-null  int64
 14  HadCOPD                    246022 non-null  int64
 15  HadDepressiveDisorder      246022 non-null  int64
 16  HadKidneyDisease           246022 non-null  int64
 17  HadArthritis               246022 non-null  int64
 18  HadDiabetes                246022 non-null  object
 19  DeafOrHardOfHearing        246022 non-null  int64
 20  BlindOrVisionDifficulty    246022 non-null  int64
 21  DifficultyConcentrating    246022 non-null  int64
 22  DifficultyWalking          246022 non-null  int64
 23  DifficultyDressingBathing  246022 non-null  int64
 24  DifficultyErrands          246022 non-null  int64
 25  SmokerStatus               246022 non-null  object
 26  ECigaretteUsage            246022 non-null  object
 27  ChestScan                  246022 non-null  int64
 28  RaceEthnicityCategory      246022 non-null  object
 29  AgeCategory                246022 non-null  object
 30  HeightInMeters             246022 non-null  float64
 31  WeightInKilograms          246022 non-null  float64
 32  BMI                        246022 non-null  float64
 33  AlcoholDrinkers            246022 non-null  int64
 34  HIVTesting                 246022 non-null  int64
 35  FluVaxLast12               246022 non-null  int64
 36  PneumoVaxEver              246022 non-null  int64
 37  TetanusLast10Tdap          246022 non-null  object
 38  HighRiskLastYear           246022 non-null  int64
 39  CovidPos                   246022 non-null  object
dtypes: float64(6), int64(23), object(11)
memory usage: 75.1+ MB

In [196]:
# dropping unwanted columns

df_cd = df_nn.drop(['RemovedTeeth','State', 'DifficultyWalking','DifficultyConcentrating','BlindOrVisionDifficulty','DifficultyDressingBathing','ECigaretteUsage','DeafOrHardOfHearing','HadSkinCancer','ChestScan','RaceEthnicityCategory','HIVTesting','PneumoVaxEver','HighRiskLastYear','CovidPos'],axis=1)

In [198]:
df_cd.head()

,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,HadHeartAttack,HadAngina,HadStroke,...,HadDiabetes,DifficultyErrands,SmokerStatus,AgeCategory,HeightInMeters,WeightInKilograms,BMI,AlcoholDrinkers,FluVaxLast12,TetanusLast10Tdap
0,0,Very good,4.0,0.0,Within past year (anytime less than 12 months ...,1,9.0,0,0,0,...,No,0,Former smoker,Age 65 to 69,1.60,71.67,27.99,0,1,"Yes, received Tdap"
1,1,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,1,6.0,0,0,0,...,Yes,0,Former smoker,Age 70 to 74,1.78,95.25,30.13,0,1,"Yes, received tetanus shot but not sure what type"
2,1,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,0,8.0,0,0,0,...,No,0,Former smoker,Age 75 to 79,1.85,108.86,31.66,1,0,"No, did not receive any tetanus shot in the pa..."
3,0,Fair,5.0,0.0,Within past year (anytime less than 12 months ...,1,9.0,0,0,0,...,No,0,Never smoked,Age 80 or older,1.70,90.72,31.32,0,1,"No, did not receive any tetanus shot in the pa..."
4,0,Good,3.0,15.0,Within past year (anytime less than 12 months ...,1,5.0,0,0,0,...,No,0,Never smoked,Age 80 or older,1.55,79.38,33.07,0,1,"No, did not receive any tetanus shot in the pa..."

In [199]:
df_cd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246022 entries, 0 to 246021
Data columns (total 25 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Sex                    246022 non-null  int64
 1   GeneralHealth          246022 non-null  object
 2   PhysicalHealthDays     246022 non-null  float64
 3   MentalHealthDays       246022 non-null  float64
 4   LastCheckupTime        246022 non-null  object
 5   PhysicalActivities     246022 non-null  int64
 6   SleepHours             246022 non-null  float64
 7   HadHeartAttack         246022 non-null  int64
 8   HadAngina              246022 non-null  int64
 9   HadStroke              246022 non-null  int64
 10  HadAsthma              246022 non-null  int64
 11  HadCOPD                246022 non-null  int64
 12  HadDepressiveDisorder  246022 non-null  int64
 13  HadKidneyDisease       246022 non-null  int64
 14  HadArthritis           246022 non-null  int64
 15  HadDiabetes            246022 non-null  object
 16  DifficultyErrands      246022 non-null  int64
 17  SmokerStatus           246022 non-null  object
 18  AgeCategory            246022 non-null  object
 19  HeightInMeters         246022 non-null  float64
 20  WeightInKilograms      246022 non-null  float64
 21  BMI                    246022 non-null  float64
 22  AlcoholDrinkers        246022 non-null  int64
 23  FluVaxLast12           246022 non-null  int64
 24  TetanusLast10Tdap      246022 non-null  object
dtypes: float64(6), int64(13), object(6)
memory usage: 46.9+ MB

In [200]:
categorical_columns = df_cd.select_dtypes(include=['object']).columns.tolist()

In [201]:
categorical_columns

['GeneralHealth',
 'LastCheckupTime',
 'HadDiabetes',
 'SmokerStatus',
 'AgeCategory',
 'TetanusLast10Tdap']

In [202]:
from sklearn.preprocessing import OneHotEncoder

In [203]:
encoder = OneHotEncoder(handle_unknown = 'ignore')

In [204]:
one_hot_encoded = encoder.fit_transform(df_cd[categorical_columns]).toarray()

In [205]:
encoder.get_feature_names_out(categorical_columns)

array(['GeneralHealth_Excellent', 'GeneralHealth_Fair',
       'GeneralHealth_Good', 'GeneralHealth_Poor',
       'GeneralHealth_Very good', 'LastCheckupTime_5 or more years ago',
       'LastCheckupTime_Within past 2 years (1 year but less than 2 years ago)',
       'LastCheckupTime_Within past 5 years (2 years but less than 5 years ago)',
       'LastCheckupTime_Within past year (anytime less than 12 months ago)',
       'HadDiabetes_No',
       'HadDiabetes_No, pre-diabetes or borderline diabetes',
       'HadDiabetes_Yes',
       'HadDiabetes_Yes, but only during pregnancy (female)',
       'SmokerStatus_Current smoker - now smokes every day',
       'SmokerStatus_Current smoker - now smokes some days',
       'SmokerStatus_Former smoker', 'SmokerStatus_Never smoked',
       'AgeCategory_Age 18 to 24', 'AgeCategory_Age 25 to 29',
       'AgeCategory_Age 30 to 34', 'AgeCategory_Age 35 to 39',
       'AgeCategory_Age 40 to 44', 'AgeCategory_Age 45 to 49',
       'AgeCategory_Age 50 to 54', 'AgeCategory_Age 55 to 59',
       'AgeCategory_Age 60 to 64', 'AgeCategory_Age 65 to 69',
       'AgeCategory_Age 70 to 74', 'AgeCategory_Age 75 to 79',
       'AgeCategory_Age 80 or older',
       'TetanusLast10Tdap_No, did not receive any tetanus shot in the past 10 years',
       'TetanusLast10Tdap_Yes, received Tdap',
       'TetanusLast10Tdap_Yes, received tetanus shot but not sure what type',
       'TetanusLast10Tdap_Yes, received tetanus shot, but not Tdap'],
      dtype=object)

In [206]:
one_hot_df = pd.DataFrame(one_hot_encoded,columns=encoder.get_feature_names_out(categorical_columns))

In [207]:
one_hot_df.shape

(246022, 34)

In [208]:
for i in one_hot_df.columns:
    if i in df_cd.columns:
        print(i)

In [209]:
df_cd.drop(categorical_columns, axis=1).shape

(246022, 19)

In [210]:
df_encoded = pd.concat([df_cd.drop(categorical_columns, axis=1).reset_index(drop = True),one_hot_df], axis=1)

In [211]:
df_encoded.shape

(246022, 53)

In [212]:
df_encoded.head()

,Sex,PhysicalHealthDays,MentalHealthDays,PhysicalActivities,SleepHours,HadHeartAttack,HadAngina,HadStroke,HadAsthma,HadCOPD,...,AgeCategory_Age 55 to 59,AgeCategory_Age 60 to 64,AgeCategory_Age 65 to 69,AgeCategory_Age 70 to 74,AgeCategory_Age 75 to 79,AgeCategory_Age 80 or older,"TetanusLast10Tdap_No, did not receive any tetanus shot in the past 10 years","TetanusLast10Tdap_Yes, received Tdap","TetanusLast10Tdap_Yes, received tetanus shot but not sure what type","TetanusLast10Tdap_Yes, received tetanus shot, but not Tdap"
0,0,4.0,0.0,1,9.0,0,0,0,0,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,1,0.0,0.0,1,6.0,0,0,0,0,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,0.0,0.0,0,8.0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
3,0,5.0,0.0,1,9.0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
4,0,3.0,15.0,1,5.0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0

In [213]:
df_encoded.to_csv('Data\cleaned_data1.csv',index=False)

In [214]:
df = df_encoded.sample(frac = 0.1)

In [215]:
df.head()

,Sex,PhysicalHealthDays,MentalHealthDays,PhysicalActivities,SleepHours,HadHeartAttack,HadAngina,HadStroke,HadAsthma,HadCOPD,...,AgeCategory_Age 55 to 59,AgeCategory_Age 60 to 64,AgeCategory_Age 65 to 69,AgeCategory_Age 70 to 74,AgeCategory_Age 75 to 79,AgeCategory_Age 80 or older,"TetanusLast10Tdap_No, did not receive any tetanus shot in the past 10 years","TetanusLast10Tdap_Yes, received Tdap","TetanusLast10Tdap_Yes, received tetanus shot but not sure what type","TetanusLast10Tdap_Yes, received tetanus shot, but not Tdap"
24559,1,14.0,5.0,1,8.0,0,0,0,0,0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
208996,0,1.0,0.0,0,8.0,0,0,0,1,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
187878,0,0.0,15.0,1,6.0,0,0,0,0,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
58954,1,5.0,0.0,1,6.0,0,0,0,0,1,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
54675,0,2.0,15.0,1,6.0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [216]:
X = df.drop(['HadHeartAttack'],axis=1)

In [217]:
X.shape

(24602, 52)

In [218]:
y = df['HadHeartAttack']

In [219]:
X_train, X_test, y_train, y_test = train_test_split(X,y , 
                                   random_state=98,  
                                   test_size=0.20,  
                                   shuffle=True)

In [220]:
from sklearn.svm import SVC

In [221]:
X_train.head()

,Sex,PhysicalHealthDays,MentalHealthDays,PhysicalActivities,SleepHours,HadAngina,HadStroke,HadAsthma,HadCOPD,HadDepressiveDisorder,...,AgeCategory_Age 55 to 59,AgeCategory_Age 60 to 64,AgeCategory_Age 65 to 69,AgeCategory_Age 70 to 74,AgeCategory_Age 75 to 79,AgeCategory_Age 80 or older,"TetanusLast10Tdap_No, did not receive any tetanus shot in the past 10 years","TetanusLast10Tdap_Yes, received Tdap","TetanusLast10Tdap_Yes, received tetanus shot but not sure what type","TetanusLast10Tdap_Yes, received tetanus shot, but not Tdap"
147551,1,4.0,1.0,1,7.0,0,0,1,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
73570,1,30.0,15.0,1,5.0,0,0,1,0,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
97371,0,0.0,2.0,1,7.0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
214118,0,0.0,0.0,1,7.0,0,0,0,0,1,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
165976,0,14.0,0.0,1,8.0,0,0,0,0,0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [222]:
len(X_test)

4921

In [223]:
model = SVC(kernel="rbf", gamma=0.5, C=1.0)

In [224]:
print(model)

SVC(gamma=0.5)

In [225]:
model.fit(X_train,y_train)

SVC(gamma=0.5)

In [226]:
model.score(X_test,y_test)

0.9435074171916277

In [227]:
y_pred = model.predict(X_test)

In [228]:
from sklearn import metrics

# Model Accuracy: how often is the classifier correct?
metrics.accuracy_score(y_test, y_pred)

0.9435074171916277

In [229]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [230]:
from sklearn.metrics import confusion_matrix

In [231]:
cm = confusion_matrix(y_test,y_pred)

In [232]:
cm

array([[4643,    0],
       [ 278,    0]], dtype=int64)

In [236]:
input = """
1	5	0	5	0	0	0	0	0	1	0	1.88	115.67	32.74	0	1	0	0	1	0	0	0	0	0	1	0	1	1	0	0	0	1	0	0	0	0	0	0	0	0	0	0	0	1	0	0	0	0	0	0	1	0
"""

lst = input.split()

In [237]:
lstint = [float(x) for x in lst]

In [238]:
 p = model.predict(np.reshape(lstint,(1,-1)))

C:\Users\ramas\anaconda3\envs\machine_learning\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

In [239]:
p

array([0], dtype=int64)